
build:
 version: "2.0"

accounts:
 message: "Welcome to entailment accounts related QA APIs"
 contactDetails:
  name: "Deepak Pareek QA Lead"
  email: "dpareek@entailment.com"
 onCallSupport:
  -(444)5555-3456
  -(222)6666-3234