
build:
 version: "1.0"

accounts:
 message: "Welcome to entailment accounts related PROD-docker APIs"
 contactDetails:
  name: "Deepak Pareek Product Owner"
  email: "dpareek@entailment.com"
 onCallSupport:
  -(111)5555-3456
  -(999)6666-3234
