  
build:
 version: "3.0"

cards:
 message: "Welcome to entailment cards related APIs"
 contactDetails:
  name: "Deepak Pareek"
  email: "dpareek@entailment.com"
 onCallSupport:
  -(444)1345-3456
  -(222)4566-3234
