
build:
 version: "1.0"

loans:
 message: "Welcome to entailment loans related PROD APIs"
 contactDetails:
  name: "Deepak Pareek Product Owner"
  email: "dpareek@entailment.com"
 onCallSupport:
  -(111)5555-3456
  -(999)6666-3234