services:
 configserver:
  image: "deepakpareek1/configserver:s1"
  container_name: configserver-ms
  ports:
   - "8071:8071"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
   - entailment
 accounts:
  image: "deepakpareek1/accounts:s1"
  container_name: accounts-ms
  ports:
   - "8080:8080"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
   - entailment
  environment:
   SPRING_APPLICATION_NAME: accounts
   SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
   SPRING_PROFILES__ACTIVE: default
 loans:
  image: "deepakpareek1/loans:s1"
  container_name: loans-ms
  ports:
   - "8090:8090"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
   - entailment
  environment:
   SPRING_APPLICATION_NAME: loans
   SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
   SPRING_PROFILES__ACTIVE: default
 cards:
  image: "deepakpareek1/cards:s1"
  container_name: cards-ms
  ports:
   - "9000:9000"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
   - entailment
  environment:
   SPRING_APPLICATION_NAME: cards
   SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
   SPRING_PROFILES__ACTIVE: default
networks:
  entailment:
    driver: "bridge"